version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: atomicboo/honkbot_build
    steps:
      - checkout
      - run: bazel test //...
      - run: 'bazel build //myrulebot:app_deploy.jar'