version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: atomicboo/honkbot_build
    steps:
      - checkout
      - run: touch ./myrulebot/src/main/resources/serviceAccount.json 
      - run: echo $HONKBOT_FIREBASE_SERVICE | base64 --decode > ./myrulebot/src/main/resources/serviceAccount.json
      - run: bazel test //...
      - run: 'bazel build //myrulebot:app_deploy.jar'
      - run: 'docker build -t atomicboo/rulebot:latest --build-arg HONKBOT_TOKEN=${HONKBOT_TOKEN} .'
      - run: 'docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN && docker push atomicboo/rulebot:latest'